language: julia
os:
  - linux
  - osx
git:
  depth: 3
julia:
  - release
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
